Feature/nafis vw locations nav
NafisAli/volkswagen-header-navigation pull request #4
Opened 2021-06-02 09:22 UTC by NafisAli

## Description

> **Volkswagen Header with Address Bar and Navigation Menu - Nafis**
> 
> This is a continuation of my version of the protoype for new Volkswagen Header + Navigation using only Flexbox. In this update address bar and navigation menu have been added. The theme of contained header elements and extending lines have been preserved, along with transition effects on hover. Additionally, Volkswagen fonts are now added from externally hosted source and used everywhere. Media Query mixins were used to handle different breakpoints.
> 

## Instructions

> - Run "nvm install" and "nvm use" to be on correct node verision (Windows users follow instructions [here](https://github.com/coreybutler/nvm-windows).)
> - Run "yarn install" to get all necessary packages
> - Run "yarn watch:sass" to compile CSS (Must also be done for project subfolders)
> - Run "yarn start" to start live server and launch project in browser
> 
> *Users in Windows platform can use windows specific scripts. Check package.json for details*

## Checklist

Make sure the following tasks have been completed before you submit this pull request:

- [x] Used mixins and variables to avoid unnecessary code duplication .
- [x] SCSS partial name should have `_underscores`.
- [x] Indentation follows style guide (4 spaces hard tabs HTML and CSS).
- [x] Only classes styled (not element selectors).
- [x] All elements have classes.
- [x] Class names are meaningful and consistent.
- [x] Class names follow style guidelines.
- [x] Style rules follow markup order.
- [x] Deleted unused css properties.
- [x] No duplicate class names in SCSS partials.
- [x] No duplicate properties within a rule.
- [ ] ~~Validated markup wih w3C Validator.~~
- [ ] ~~Tested and fixed fonts.~~
- [x] Added `.gitignore` file.
- [ ] ~~Fixed browser console errors.~~
- [ ] ~~Used ruler to match (as best as possible) height and width of items.~~
- [x] Compared front-end with mock up side by side.
- [x] Tested local production `production.css`.
- [x] Tested on mobile, preferably iOS Safari or equivalent Android.
- [x] Tested in Chrome.
- [ ] Tested in Firefox.
- [ ] Tested in Edge, if available.
- [x] Merged `develop` into your feature branch, multiple times as needed.

2021-06-03 06:59 UTC, pixelsoup requested changes
As discussed

2021-06-09 03:00 UTC, pixelsoup requested changes
Hi @NafisAli All good. 

1. I've added a few small suggestions to fix. Please continue.
3. add the vehicle drop down and style

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_box-layout.scss
> +.boxRL {
```suggestion
.boxRl {
```

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_mixins-animations.scss
> +@mixin transitionEaseIn($property, $duration, $delay) {
@NafisAli Please don't use these transition mixins. I would prefer you write them by hand using the shorthand syntax.
```css
transition: background-color 150ms ease-in-out;
```

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_mixins-animations.scss
> +@mixin transitionEaseInAll($duration, $delay) {
Please don't use `transition-property: all;` unless absolutely necessary.

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +			@include transitionEaseInAll($transition-duration, null);
Please don't use `transition-property: all;` unless absolutely necessary.

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +	@include transitionEaseInAll($transition-duration, null);
Please don't use `transition-property: all;` unless absolutely necessary.

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_mixins-fonts.scss
> +	font-family: "VWHeadLight", arial, verdana, sans-serif;
All `font-family` fallbacks: Please add Helvetica instead of Verdana as one of the fallbacks and use Helvetica before Arial.
```suggestion
	font-family: "VWHeadLight", Helvetica, Arial, sans-serif;
```

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +
Please remove line break before mixin. This is not a new [declaration block](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#css_declaration_blocks) so shouldn't have a space before

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +
Please remove line break before mixin.

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_pages.scss
> +.container {
Please rename this partial `_container.scss`

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_variables.scss
>  // Variables
Please delete `comment`

2021-06-09 03:00 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/production.scss
> +@import "mixins-animations";
Please alphabetise each section
```css
@import "external-fonts";
@import "mixins-animations";
@import "mixins-fonts";
@import "mixins-media-queries";
```

2021-06-09 04:29 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_mixins-animations.scss
> +@mixin transitionEaseIn($property, $duration, $delay) {
Resolved in 8e44318

2021-06-09 04:29 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_mixins-animations.scss
> +@mixin transitionEaseInAll($duration, $delay) {
Resolved in 8e44318

2021-06-09 04:29 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +			@include transitionEaseInAll($transition-duration, null);
Resolved in 8e44318

2021-06-09 04:29 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +	@include transitionEaseInAll($transition-duration, null);
Resolved in 8e44318

2021-06-09 04:30 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +
Resolved in 8e44318

2021-06-09 04:30 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_module-header-address-bar.scss
> +
Resolved in 8e44318

2021-06-09 04:34 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_pages.scss
> +.container {
Resolved in ec6a781

2021-06-09 04:34 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/production.scss
> +@import "mixins-animations";
Resolved in ec6a781

2021-06-09 04:37 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_variables.scss
>  // Variables
Resolved in ef6caae

2021-06-09 04:40 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_mixins-fonts.scss
> +	font-family: "VWHeadLight", arial, verdana, sans-serif;
Update all font mixins with suggested fallbacks: acaa80f

2021-06-11 02:05 UTC, pixelsoup requested changes

2021-06-11 02:05 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header-brand-dealership.scss
> +.brandDealership {
Refactor class name to indicate it's a parent wrapper
```suggestion
.brandDealershipWrapper {
```

2021-06-11 02:05 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header-brand-dealership.scss
> +.dealerName {
Refactor class name to indicate it's text
```suggestion
.dealerNameText {
```

2021-06-11 02:05 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header-navigation.scss
> -.headerNavigationWrapper {
Suggested classNames
`.navPrimaryWrapper`
~~`.navigationMenuWrapper`~~
  `.navPrimaryList`
   ` .navPrimaryItem`
     ` .navPrimaryLink`

2021-06-11 02:05 UTC, pixelsoup commented on nafis-vw-header/includes/css/scss/_module-header.scss
> +.headerInformation {
```suggestion
.headerWrapper {
```

2021-06-11 02:57 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_module-header.scss
> +.headerInformation {
Resolved in c1c2ce4

2021-06-11 03:05 UTC, NafisAli commented on nafis-vw-header/includes/css/scss/_module-header-navigation.scss
> -.headerNavigationWrapper {
Resolved in 8a91bd3

2021-06-11 03:06 UTC, merged